version: '3'
services:
  xxljob:
    image: docker.io/xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob
    depends_on:
      - mysql8
    volumes:
      - /home/logs/xxl-job/applogs:/data/applogs
    ports:
      - 9908:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://192.168.1.111:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=root@123 --xxl.job.login.username=admin --xxl.job.login.password=admin@123'
    networks:
      - xxl-job-admin
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  xxl-job-admin:
    driver: bridge