# Use root/example as user/password credentials
# https://hub.docker.com/_/mongo
version: '3.1'

services:

  mongo:
    image: mongo:5.0.3
    restart: always
    ports: 
    - 27017:27017
    volumes:
    - /data/mongodata/data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    command: --wiredTigerCacheSizeGB 0.8 
    # --config /etc/mongo/mongod.conf

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_SITE_BASEURL: /mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:pwd@mongo:27017/