version: "2.1"
services:
  main:
    image: ${ALPINE_DOCKER_IMAGE_NAME:-ubuntu}
    expose:
      - "8888"
      - "7777"
    ports:
      - "8888:8888"
      - "7777:7777"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=jiushi
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf:/usr/local/share/camilla
      - ./camilla:/usr/local/bin/camilla
    command: /usr/local/bin/camilla


